### ISSUE TITLE
js error on extend-type cljs.core.IFn

### ISSUE THREAD

**Issue by dustingetz** [funcool/cats#116] opened 2015-10-24 01:08 UTC
`TypeError: Cannot set property 'cats$protocols$Contextual$' of undefined` happens on evaluating this form:
```clojure
(extend-type #?(:clj clojure.lang.IFn
                :cljs cljs.core.IFn)
  p/Contextual
  (-get-context [_] function-context))
```

**Comment by dustingetz** [comment] 2015-10-24 01:09
I'm running on master: `af0751a Merge pull request #109 from funcool/printing`

**Comment by niwinz** [comment] 2015-10-24 07:13
Very strange, because the tests passes correctly. Can you clear your compilation cache and rebuild it again?

**Comment by yurrriq** [comment] 2015-10-28 01:37
While I'm unable to reproduce the error at the moment, [this form][1], just after where @dustingetz said the error happens, looks suspicious to me:

```clojure
#?(:cljs
   (extend-type function
     p/Contextual
     (-get-context [_] function-context)))
```

There's no var called `function`, so I don't see how that can work.

[1]: https://github.com/funcool/cats/blob/af0751a473fcfa379f03d6b65af2462e1988ad1f/src/cats/builtin.cljc#L358-L361

**Comment by yurrriq** [comment] 2015-12-16 06:28
@dustingetz, are you still getting the error on [1.2.0](https://github.com/funcool/cats/releases/tag/1.2.0)?

**Comment by yurrriq** [comment] 2016-02-16 09:45
Is this one safe to close?

**Comment by dialelo** [comment] 2016-02-16 09:55
Let's reopen it if it happens again, closing for now.

**Closed by dialelo** 2016-02-16 09:55 UTC

**Comment by yurrriq** [comment] 2016-02-16 09:58
:+1:
